spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create

  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

storage: uploads

server:
  error:
    include-message: always
